version: '3.8'
name: food_delivery
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - "6379:6379"
  redis_insight:
    container_name: redis_insight
    image: redislabs/redisinsight
    restart: always
    ports:
      - "8001:8001"
    
